apiVersion: apps/v1
kind: Deployment
metadata:
  name: khcm-receiver-test-1
  namespace: monitoring
spec:
  replicas: 250
  selector:
    matchLabels:
      app: khttp-connectivity-monitor
      mode: receiver
      test: test-1
  template:
    metadata:
      labels:
        app: khttp-connectivity-monitor
        mode: receiver
        test: test-1
    spec:
      containers:
      - name: khttp-connectivity-monitor
        image: "kwarunek/khttp-connectivity-monitor:0.0.2-dev1"
        ports:
        - containerPort: 9999
        env:
        - name: PAAS_MONITORING_KEY
          value: m-dlpaonpr-538318bb-mon-c2a
        - name: KHTTP_PORT
          value: "9999"
        - name: KHTTP_HOST
          value: "0.0.0.0"
        - name: KHTTP_MODE
          value: receiver
        - name: KHTTP_CLUSTERNAME
          value: c2p
        - name: KHTTP_NODE
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
