apiVersion: v1
kind: Service
metadata:
  name: khcm-receiver-test-1
spec:
  selector:
    app: khttp-connectivity-monitor
    mode: receiver
    test: test-1
  ports:
    - protocol: TCP
      port: 9999
      targetPort: 9999
  type: ClusterIP

